[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  # Environment variables will be set in Netlify dashboard
  # EXPO_PUBLIC_SUPABASE_URL = "https://zvoavkzruhnzzeqyihrc.supabase.co"
  # EXPO_PUBLIC_SUPABASE_ANON_KEY = "your_supabase_anon_key_here"

# Handle client-side routing for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
